version: '3.0'

services:
  peer1:
    container_name: peer1
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      HTTP_PORT: 5001
      P2P_PORT: 6001
    stdin_open: true
    tty: true


  peer2:
    container_name: peer2
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      HTTP_PORT: 5002
      P2P_PORT: 6002
    ports:
      - "5002:5002"
    stdin_open: true
    tty: true